### ISSUE TITLE
Embeddable tools / lists

### ISSUE THREAD

**Issue by chrishutchinson** [journalisttoolbox/journalisttoolbox-front-end#90] opened 2015-11-27 14:56 UTC
Did we ever get chance to make progress on this feature? I can probably look into this if there are some API endpoints I can read from!

**Comment by nevosegal** [comment] 2016-09-05 09:29
Duplicate of #56.
We haven't made any progress on this. If people feel this is an important feature I can definitely look into it more thoroughly. Let's continue the discussion on #56.

**Closed as completed by nevosegal** 2016-09-05 09:29 UTC
Labels: enhancement
